spring.application.name=backend
spring.profiles.active=dev

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cors.origin=${CORS_ORIGIN:http://localhost:3000}
ml.service.url=${ML_SERVICE_URL:http://127.0.0.1:8000}
